use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::Hasher;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let output_rs = out_dir.join("embedded_docs_generated.rs");

    let project_root = manifest_dir.join("..").join("..");
    let project_root = project_root.canonicalize().unwrap_or(project_root);

    let mut files: Vec<(String, PathBuf)> = Vec::new();

    let readme_path = project_root.join("README.md");
    files.push(("README.md".to_string(), readme_path));

    collect_text_files(&project_root.join("docs"), &project_root, &mut files);
    collect_text_files(&project_root.join("examples"), &project_root, &mut files);

    files.sort_by(|a, b| a.0.cmp(&b.0));

    // Compute content hash for versioning
    let mut hasher = DefaultHasher::new();
    for (relative_path, abs_path) in &files {
        if let Ok(content) = fs::read_to_string(abs_path) {
            hasher.write(content.as_bytes());
        }
        hasher.write(relative_path.as_bytes());
    }
    let version = format!("h{:016x}", hasher.finish());

    let mut code = String::from("// Auto-generated by build.rs. Do not edit.\n\n");
    code.push_str("pub const EMBEDDED_VERSION: &str = \"");
    code.push_str(&version);
    code.push_str("\";\n\n");
    code.push_str("pub struct EmbeddedFile {\n");
    code.push_str("    pub relative_path: &'static str,\n");
    code.push_str("    pub content: &'static str,\n");
    code.push_str("}\n\n");
    code.push_str("pub const EMBEDDED_FILES: &[EmbeddedFile] = &[\n");

    for (relative_path, abs_path) in &files {
        let abs_str = abs_path.to_string_lossy();
        code.push_str(&format!(
            "    EmbeddedFile {{ relative_path: {relative_path:?}, content: include_str!({abs_str:?}) }},\n",
        ));
    }

    code.push_str("];\n");

    fs::write(&output_rs, &code).unwrap();

    println!("cargo::rerun-if-changed=README.md");
    println!("cargo::rerun-if-changed=docs/");
    println!("cargo::rerun-if-changed=examples/");
}

fn collect_text_files(dir: &PathBuf, project_root: &PathBuf, files: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_text_files(&path, project_root, files);
        } else if is_text_file(&path) {
            if let Ok(relative) = path.strip_prefix(project_root) {
                let rel_str = relative.to_string_lossy().to_string().replace('\\', "/");
                files.push((rel_str, path));
            }
        }
    }
}

fn is_text_file(path: &std::path::Path) -> bool {
    match path.extension().and_then(|e| e.to_str()) {
        Some("md") | Some("json") | Some("rules") => true,
        _ => false,
    }
}
